src/views/MainView.py
from flask import Blueprint, render_template, redirect, url_for


BP = Blueprint("Main", __name__,
               url_prefix = "/main",
               template_folder = "../templates",
               static_folder = "../static"
               )

@BP.route("/")
def RevivedWitch_Main():
    return render_template("Main/MainPage.html")

src/views/SimulatorView.py
import json
import os
import time

from flask import Blueprint, redirect, render_template, url_for, session, request, jsonify
from urllib.parse import quote

from database.models.gacha_banner_model import BannerData
from database.models.chest_gacha_banner_model import ChestGachaBannerData
from src.functions.DataTools import DataTools
from src.functions.ImageTools import ImageTools
from src.functions.Simulator import Simulator
import base64
import uuid


BP = Blueprint("Simulator", __name__,
               url_prefix = "/simulator",
               template_folder = "../templates",
               static_folder = "../static"
               )


@BP.route("/", methods = ["GET", "POST"])
def Simulator_Main():
    if request.method == "GET":
        if session.get("banner") != session.get("bf_banner"):
            print(f"current banner : {session.get('banner')}")
            print(f"before banner : {session.get('bf_banner')}")

            print("gacha_count 값 초기화 진행")
            session["gacha_count"] = 0
            session["gacha_count_half"] = 0
            session["gacha_count_full"] = 0
        return render_template("Simulator/Simulator.html", result_img = None)
    else:
        banner_name = session.get("banner")
        if "gacha_count" not in session.keys():
            if banner_name == "레전더리 장비 상자":
                print("gacha_count의 값을 1을 추가")
                session["gacha_count"] = 1

            else:
                print("gacha_count의 값을 10으로 지정")
                session["gacha_count"] = 10
                session["gacha_count_half"] = 10
                session["gacha_count_full"] = 10
        else:
            if banner_name == "레전더리 장비 상자":
                print("gacha_count의 값을 1을 추가")
                session["gacha_count"] += 1

            else:
                print("gacha_count의 값을 10을 추가")
                session["gacha_count"] += 10
                session["gacha_count_half"] += 10
                session["gacha_count_full"] += 10
                print(f"gacha_count : {session.get('gacha_count')}")

        simulator = Simulator(
            banner_name = "영혼 소환" if banner_name is None else banner_name
        )

        if simulator.SIMULATOR_BANNET_TYPE == BannerData:
            current_banner_data = DataTools.GetBannerDataByBannerName(banner_name = banner_name)
            print(f"is pickup banner? : {current_banner_data.PickUpData.get('active')}")
            # gacha_result_doll_list = simulator.SimulatePickUpGacha(
            #     session=session
            # )

            gacha_result_doll_list = simulator.SimulateGacha()
            # if current_banner_data.PickUpData.get("active"):
            #     gacha_result_doll_list = simulator.SimulatePickUpGacha(
            #         session = session
            #     )
            #
            # else:
            #     gacha_result_doll_list = simulator.SimulateGacha()




            session["gacha_result_list"] = {}
            response_use_data = {}
            for item_data_idx in range(len(gacha_result_doll_list)):
                item_data = gacha_result_doll_list[item_data_idx]
                gacha_num = item_data_idx + 1
                session[f"{gacha_num}"] = item_data.GetAllDollData()
                response_use_data[f"{gacha_num}"] = item_data.GetAllDollData()


            IT = ImageTools()
            gacha_result_img = IT.MergeGachaBgImage(doll_object_list=gacha_result_doll_list)
            img_name = uuid.uuid4()

            # img_save_dir = os.path.dirname(os.path.dirname())
            from app import BASE_DIR
            img_save_dir = BASE_DIR + f"/static/img/gacha/result/{img_name}.png"
            f_time = time.perf_counter()
            gacha_result_img.save(img_save_dir)
            s_time = time.perf_counter()

            print(f"gacha_result_img.save() 소요시간 : {s_time - f_time}s")
            # encoded_gacha_result_img = base64.b64encode(gacha_result_img.tobytes()).decode()
            return_data = {
                "src": f"../static/img/gacha/result/{img_name}.png",
                "name": f"{img_name}",
                "result": response_use_data,
                "current_gacha_amount": session.get("gacha_count")
            }
            return jsonify(result_data = return_data)

        elif simulator.SIMULATOR_BANNET_TYPE == ChestGachaBannerData:
            gacha_result_item_object = simulator.SimulateChestGacha()
            image_tools = ImageTools()
            gacha_result_image = image_tools.MergeItemGachaBgImage(item_object = gacha_result_item_object)
            img_name = uuid.uuid4()
            from app import BASE_DIR
            gacha_result_image.save(BASE_DIR + f"/static/img/gacha/result/{img_name}.png")

            response_use_data = {}
            result_list = [gacha_result_item_object]
            for item_data_idx in range(len(result_list)):
                item_data = result_list[item_data_idx]
                gacha_num = item_data_idx + 1
                session[f"{gacha_num}"] = item_data.GetAllItemEquipmentData()
                response_use_data[f"{gacha_num}"] = item_data.GetAllItemEquipmentData()

            return_data = {
                "src": f"../static/img/gacha/result/{img_name}.png",
                "name": f"{img_name}",
                "result": response_use_data,
                "current_gacha_amount": session.get("gacha_count")
            }
            # with open("chest_item_data.json", "w") as write_file:
            #     json.dump(return_data, write_file, indent = 4)
            return jsonify(result_data = return_data)


@BP.route("/soul")
def Simulator_Main_Soul():
    session["bf_banner"] = session.get("banner")
    session["banner"] = f"영혼 소환"

    return redirect(url_for("Simulator.Simulator_Main"))


@BP.route("/mercury")
def Simulator_Main_Mercury():
    session["bf_banner"] = session.get("banner")
    session["banner"] = f"수은 원소 소환"

    return redirect(url_for("Simulator.Simulator_Main"))


@BP.route("/brimstone")
def Simulator_Main_Brimstone():
    session["bf_banner"] = session.get("banner")
    session["banner"] = f"유황 원소 소환"

    return redirect(url_for("Simulator.Simulator_Main"))


@BP.route("/saltstone")
def Simulator_Main_Saltstone():
    session["bf_banner"] = session.get("banner")
    session["banner"] = f"염석 원소 소환"

    return redirect(url_for("Simulator.Simulator_Main"))


@BP.route("/dream")
def Simulator_Main_Dream():
    session["bf_banner"] = session.get("banner")
    session["banner"] = f"꿈의 소환"

    return redirect(url_for("Simulator.Simulator_Main"))

@BP.route("/chest")
def Simulator_Main_Chest():
    session["bf_banner"] = session.get("banner")
    session["banner"] = f"레전더리 장비 상자"

    return redirect(url_for("Simulator.Simulator_Main"))

@BP.route("/stack_clear")
def Simulator_Main_StackClear():
    session["gacha_count"] = 0
    session["gacha_count_half"] = 0
    session["gacha_count_full"] = 0

    return redirect(url_for("Simulator.Simulator_Main"))
# @BP.route("/<img_file_bin>")
# def Simulator_Main_s(img_file_bin = None):
#     return render_template("Simulator/Simulator.html", img_file_bin = img_file_bin)

# @BP.route("/", methods = ["POST"])
# def Simulator_Run():
# #
#     simulator = Simulator(
#         banner_name = "영혼 소환"
#     )
#     data = request.get_json()
#     print(data)
#     print(type(data))
#
#     gacha_result_doll_list = simulator.SimulateGacha()
#     IT = ImageTools()
#     gacha_result_img = IT.MergeGachaBgImage(doll_object_list = gacha_result_doll_list)
#     encoded_gacha_result_img = base64.b64encode(gacha_result_img.tobytes()).decode("ascii")
#     return_data = {
#         "src": quote(encoded_gacha_result_img)
#     }
#
#     return jsonify(result_data = return_data)
#     # return jsonify(result = "success", rdata = return_data)
#     # return f'<img src="data:image/png;base64,{encoded_gacha_result_img}">'
#
# @BP.route("/simulate_run")
# def Test():
#     simulator = Simulator(
#         banner_name = "영혼 소환"
#     )
#     # data = request.get_json()
#     # print(data)
#     # print(type(data))
#
#     gacha_result_doll_list = simulator.SimulateGacha()
#     IT = ImageTools()
#     gacha_result_img = IT.MergeGachaBgImage(doll_object_list=gacha_result_doll_list)
#     encoded_gacha_result_img = base64.b64encode(gacha_result_img.tobytes())
#
#     # return render_template("Simulator/Simulator.html", result_img = encoded_gacha_result_img)
#     return redirect(url_for("Simulator.Simulator_Main"), result_img = encoded_gacha_result_img)

templates/Frame/RevivedWitch_WebService_BaseFrame.html
<!doctype html>
<html lang="ko">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>깨어난 마녀 가챠 시뮬레이터</title>

        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&family=Jua&display=swap" rel="stylesheet">
        <link href="../../static/css/bootstrap.min.css" rel="stylesheet">

        <style>
            a:link { text-decoration: none;}
            a:visited { text-decoration: none;}
            a:hover { text-decoration: none;}
        </style>

        {% block head %}
        {% endblock %}
    </head>
    <body>
        <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
            <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6" href="{{ url_for("Main.RevivedWitch_Main") }}"
               style="font-family: 'Black Han Sans', sans-serif;">
                <span class="position-relative">
                    깨어난 마녀 시뮬레이터
                </span>
            </a>
            <button class="navbar-toggler position-relative d-md-none collapsed " type="button" data-bs-toggle="collapse"
                    data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </header>
        <div class="container-fluid">
            <div class="row">
                <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                    <div class="position-sticky pt-3 sidebar-sticky">
                        <ul class="nav flex-column">

                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{{ url_for("Main.RevivedWitch_Main") }}" style="font-family: 'Black Han Sans', sans-serif; font-size: 25px; color: #000000">
                                    <span data-feather="home" class="align-text-bottom"></span>
                                    가챠 시뮬레이터
                                </a>
                            </li>
                        </ul>

                        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted text-uppercase">
                        <span style="font-family: 'Black Han Sans', sans-serif; font-size: 25px">소환 배너</span>
                        <a class="link-secondary" href="#" aria-label="Add a new report">
                            <span data-feather="plus-circle" class="align-text-bottom"></span>
                        </a>
                        </h6>
                        <div class="overflow-auto">
                            <ul class="nav flex-column mb-2">
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ url_for("Simulator.Simulator_Main_Dream") }}" style="font-family: 'Black Han Sans', sans-serif">
                                        <img src="../../static/img/gacha/banner/small/dream.png" style="max-width: 100%; height: auto">
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ url_for("Simulator.Simulator_Main_Soul") }}" style="font-family: 'Black Han Sans', sans-serif">
                                        <img src="../../static/img/gacha/banner/small/soul.png" style="max-width: 100%; height: auto">
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ url_for("Simulator.Simulator_Main_Brimstone") }}" style="font-family: 'Black Han Sans', sans-serif">
                                        <img src="../../static/img/gacha/banner/small/brimstone.png" style="max-width: 100%; height: auto">
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ url_for("Simulator.Simulator_Main_Mercury") }}" style="font-family: 'Black Han Sans', sans-serif">
                                        <img src="../../static/img/gacha/banner/small/mercury.png" style="max-width: 100%; height: auto">
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ url_for("Simulator.Simulator_Main_Saltstone") }}" style="font-family: 'Black Han Sans', sans-serif">
                                        <img src="../../static/img/gacha/banner/small/saltstone.png" style="max-width: 100%; height: auto">
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ url_for("Simulator.Simulator_Main_Chest") }}" style="font-family: 'Black Han Sans', sans-serif">
                                        <img src="../../static/img/gacha/banner/small/chest.png" style="max-width: 100%; height: auto">
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
                <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                    {% block content %}
                    {% endblock %}
                </main>
            </div>
        </div>

        <script src="../../static/js/bootstrap.bundle.min.js"></script>



    </body>
</html>