src/views/SimulatorView.py
import json
import os
import time

from flask import Blueprint, redirect, render_template, url_for, session, request, jsonify
from urllib.parse import quote

from database.models.gacha_banner_model import BannerData
from database.models.chest_gacha_banner_model import ChestGachaBannerData
from src.functions.DataTools import DataTools
from src.functions.ImageTools import ImageTools
from src.functions.Simulator import Simulator
import base64
import uuid


BP = Blueprint("Simulator", __name__,
               url_prefix = "/simulator",
               template_folder = "../templates",
               static_folder = "../static"
               )


@BP.route("/", methods = ["GET", "POST"])
def Simulator_Main():
    if request.method == "GET":
        if session.get("banner") != session.get("bf_banner"):
            print(f"current banner : {session.get('banner')}")
            print(f"before banner : {session.get('bf_banner')}")

            print("gacha_count 값 초기화 진행")
            session["gacha_count"] = 0
            session["gacha_count_half"] = 0
            session["gacha_count_full"] = 0
        return render_template("Simulator/Simulator.html", result_img = None)
    else:
        banner_name = session.get("banner")
        if "gacha_count" not in session.keys():
            if banner_name == "레전더리 장비 상자":
                print("gacha_count의 값을 1을 추가")
                session["gacha_count"] = 1

            else:
                print("gacha_count의 값을 10으로 지정")
                session["gacha_count"] = 10
                session["gacha_count_half"] = 10
                session["gacha_count_full"] = 10
        else:
            if banner_name == "레전더리 장비 상자":
                print("gacha_count의 값을 1을 추가")
                session["gacha_count"] += 1

            else:
                print("gacha_count의 값을 10을 추가")
                session["gacha_count"] += 10
                session["gacha_count_half"] += 10
                session["gacha_count_full"] += 10
                print(f"gacha_count : {session.get('gacha_count')}")

        simulator = Simulator(
            banner_name = "영혼 소환" if banner_name is None else banner_name
        )

        if simulator.SIMULATOR_BANNET_TYPE == BannerData:
            current_banner_data = DataTools.GetBannerDataByBannerName(banner_name = banner_name)
            print(f"is pickup banner? : {current_banner_data.PickUpData.get('active')}")
            # gacha_result_doll_list = simulator.SimulatePickUpGacha(
            #     session=session
            # )

            gacha_result_doll_list = simulator.SimulateGacha()
            # if current_banner_data.PickUpData.get("active"):
            #     gacha_result_doll_list = simulator.SimulatePickUpGacha(
            #         session = session
            #     )
            #
            # else:
            #     gacha_result_doll_list = simulator.SimulateGacha()




            session["gacha_result_list"] = {}
            response_use_data = {}
            for item_data_idx in range(len(gacha_result_doll_list)):
                item_data = gacha_result_doll_list[item_data_idx]
                gacha_num = item_data_idx + 1
                session[f"{gacha_num}"] = item_data.GetAllDollData()
                response_use_data[f"{gacha_num}"] = item_data.GetAllDollData()


            IT = ImageTools()
            gacha_result_img = IT.MergeGachaBgImage(doll_object_list=gacha_result_doll_list)
            img_name = uuid.uuid4()

            # img_save_dir = os.path.dirname(os.path.dirname())
            from app import BASE_DIR
            img_save_dir = BASE_DIR + f"/static/img/gacha/result/{img_name}.png"
            f_time = time.perf_counter()
            gacha_result_img.save(img_save_dir)
            s_time = time.perf_counter()

            print(f"gacha_result_img.save() 소요시간 : {s_time - f_time}s")
            # encoded_gacha_result_img = base64.b64encode(gacha_result_img.tobytes()).decode()
            return_data = {
                "src": f"../static/img/gacha/result/{img_name}.png",
                "name": f"{img_name}",
                "result": response_use_data,
                "current_gacha_amount": session.get("gacha_count")
            }
            return jsonify(result_data = return_data)

        elif simulator.SIMULATOR_BANNET_TYPE == ChestGachaBannerData:
            gacha_result_item_object = simulator.SimulateChestGacha()
            image_tools = ImageTools()
            gacha_result_image = image_tools.MergeItemGachaBgImage(item_object = gacha_result_item_object)
            img_name = uuid.uuid4()
            from app import BASE_DIR
            gacha_result_image.save(BASE_DIR + f"/static/img/gacha/result/{img_name}.png")

            response_use_data = {}
            result_list = [gacha_result_item_object]
            for item_data_idx in range(len(result_list)):
                item_data = result_list[item_data_idx]
                gacha_num = item_data_idx + 1
                session[f"{gacha_num}"] = item_data.GetAllItemEquipmentData()
                response_use_data[f"{gacha_num}"] = item_data.GetAllItemEquipmentData()

            return_data = {
                "src": f"../static/img/gacha/result/{img_name}.png",
                "name": f"{img_name}",
                "result": response_use_data,
                "current_gacha_amount": session.get("gacha_count")
            }
            # with open("chest_item_data.json", "w") as write_file:
            #     json.dump(return_data, write_file, indent = 4)
            return jsonify(result_data = return_data)


@BP.route("/soul")
def Simulator_Main_Soul():
    session["bf_banner"] = session.get("banner")
    session["banner"] = f"영혼 소환"

    return redirect(url_for("Simulator.Simulator_Main"))


@BP.route("/mercury")
def Simulator_Main_Mercury():
    session["bf_banner"] = session.get("banner")
    session["banner"] = f"수은 원소 소환"

    return redirect(url_for("Simulator.Simulator_Main"))


@BP.route("/brimstone")
def Simulator_Main_Brimstone():
    session["bf_banner"] = session.get("banner")
    session["banner"] = f"유황 원소 소환"

    return redirect(url_for("Simulator.Simulator_Main"))


@BP.route("/saltstone")
def Simulator_Main_Saltstone():
    session["bf_banner"] = session.get("banner")
    session["banner"] = f"염석 원소 소환"

    return redirect(url_for("Simulator.Simulator_Main"))


@BP.route("/dream")
def Simulator_Main_Dream():
    session["bf_banner"] = session.get("banner")
    session["banner"] = f"꿈의 소환"

    return redirect(url_for("Simulator.Simulator_Main"))

@BP.route("/chest")
def Simulator_Main_Chest():
    session["bf_banner"] = session.get("banner")
    session["banner"] = f"레전더리 장비 상자"

    return redirect(url_for("Simulator.Simulator_Main"))

@BP.route("/stack_clear")
def Simulator_Main_StackClear():
    session["gacha_count"] = 0
    session["gacha_count_half"] = 0
    session["gacha_count_full"] = 0

    return redirect(url_for("Simulator.Simulator_Main"))
# @BP.route("/<img_file_bin>")
# def Simulator_Main_s(img_file_bin = None):
#     return render_template("Simulator/Simulator.html", img_file_bin = img_file_bin)

# @BP.route("/", methods = ["POST"])
# def Simulator_Run():
# #
#     simulator = Simulator(
#         banner_name = "영혼 소환"
#     )
#     data = request.get_json()
#     print(data)
#     print(type(data))
#
#     gacha_result_doll_list = simulator.SimulateGacha()
#     IT = ImageTools()
#     gacha_result_img = IT.MergeGachaBgImage(doll_object_list = gacha_result_doll_list)
#     encoded_gacha_result_img = base64.b64encode(gacha_result_img.tobytes()).decode("ascii")
#     return_data = {
#         "src": quote(encoded_gacha_result_img)
#     }
#
#     return jsonify(result_data = return_data)
#     # return jsonify(result = "success", rdata = return_data)
#     # return f'<img src="data:image/png;base64,{encoded_gacha_result_img}">'
#
# @BP.route("/simulate_run")
# def Test():
#     simulator = Simulator(
#         banner_name = "영혼 소환"
#     )
#     # data = request.get_json()
#     # print(data)
#     # print(type(data))
#
#     gacha_result_doll_list = simulator.SimulateGacha()
#     IT = ImageTools()
#     gacha_result_img = IT.MergeGachaBgImage(doll_object_list=gacha_result_doll_list)
#     encoded_gacha_result_img = base64.b64encode(gacha_result_img.tobytes())
#
#     # return render_template("Simulator/Simulator.html", result_img = encoded_gacha_result_img)
#     return redirect(url_for("Simulator.Simulator_Main"), result_img = encoded_gacha_result_img)

templates/Simulator/Simulator.html
{% extends "Frame/RevivedWitch_WebService_BaseFrame.html" %}
{% block head %}
    <script src="https://code.jquery.com/jquery-latest.min.js"></script>
{% endblock %}
{% block content %}


    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        {% if session.get("banner") == None %}
            <h1 class="h2" style="font-family: 'Black Han Sans', sans-serif; margin-top: 10px">가챠 시뮬레이터 </h1>
        {% elif session.get("banner") == "꿈의 소환" %}
            <h1 class="h2" style="font-family: 'Black Han Sans', sans-serif; margin-top: 10px">가챠 시뮬레이터 - [픽업 소환]</h1>
        {% else %}
            <h1 class="h2" style="font-family: 'Black Han Sans', sans-serif; margin-top: 10px">가챠 시뮬레이터 - [{{ session.get("banner") }}]</h1>

        {% endif %}
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
                <div id="gacha_ajax">
{#                    <input type="button" class="btn btn-sm btn-outline-secondary" id="gacha_1"#}
{#                           style="font-family: 'Jua', sans-serif;  font-size: large; margin-right:8px; margin-bottom: 5px"#}
{#                           value="1회" data-gacha-amount="1">#}
                    <a href="{{ url_for("Simulator.Simulator_Main_StackClear") }}">
                        <input type="button" class="btn btn-sm btn-outline-secondary" id="stack_clear"
                               style="font-family: 'Jua', sans-serif; font-size: large; margin-left: 8px; margin-bottom: 5px"
                               value="초기화" data-gacha-amount="10">
                    </a>

                    {% if session.get("banner") == "레전더리 장비 상자" %}
                        <input type="button" class="btn btn-sm btn-outline-secondary" id="gacha_chest"
                               style="font-family: 'Jua', sans-serif; font-size: large; margin-left: 8px; margin-bottom: 5px"
                               value="1회" data-gacha-amount="1">

                        <script>
                            $('#gacha_chest').click(function (){
                                var gacha_amount = $('#gacha_chest').val()
                                var post_data = {
                                    "gacha_amount": gacha_amount
                                }
                                {#document.getElementById("gacha_result_img").src = "../static/video/gacha_normal.mp4"#}
                                $.ajax({
                                    url: {{ url_for("Simulator.Simulator_Main") }},
                                    type: 'POST',
                                    data: JSON.stringify(post_data),
                                    dataType: 'JSON',
                                    contentType: 'application/json',
                                    success: function (data) {

                                        document.getElementById("gacha_result_img").src = data.result_data["src"]
                                        var gachaResultData = data.result_data["result"]

                                        for (result_num in gachaResultData) {
                                            var item_data_dict = gachaResultData[result_num]
                                            var result_elem = document.getElementById("gacha_result_table")
                                            var data_elem_container = document.createElement("tr")
                                            
                                            var gacha_count_elem = document.createElement("td")
                                            var gacha_count_node = document.createTextNode(data.result_data["current_gacha_amount"] + parseInt(result_num) - 1)
                                            gacha_count_elem.appendChild(gacha_count_node)
                                            data_elem_container.appendChild(gacha_count_elem)
                                            
                                            var item_name_data_elem = document.createElement("td")
                                            var item_name_data_node = document.createTextNode(item_data_dict["name"])
                                            item_name_data_elem.appendChild(item_name_data_node)
                                            data_elem_container.appendChild(item_name_data_elem)
                    
                                            var item_grade_data_elem = document.createElement("td")
                                            var item_grade_data_node = document.createTextNode(item_data_dict["grade"])
                                            item_grade_data_elem.appendChild(item_grade_data_node)
                                            data_elem_container.appendChild(item_grade_data_elem)

                                            var item_point_data_elem = document.createElement("td")
                                            var item_point_data_node = document.createTextNode(item_data_dict["equip_point"])
                                            item_point_data_elem.appendChild(item_point_data_node)
                                            data_elem_container.appendChild(item_point_data_elem)

                                            result_elem.appendChild(data_elem_container)
                                        }

                                    },
                                    error: function (request, status, error) {
                                        alert("가챠 결과 이미지를 가져오는 도중에 ajax 통신에 실패하였습니다.")
                                    }
                                })
                            })
                        </script>
                    {% else %}
                        <input type="button" class="btn btn-sm btn-outline-secondary" id="gacha_10"
                               style="font-family: 'Jua', sans-serif; font-size: large; margin-left: 8px; margin-bottom: 5px"
                               value="10회" data-gacha-amount="10">

                        <script>
                            $('#gacha_10').click(function (){
                                var gacha_amount = $('#gacha_10').val()
                                var post_data = {
                                    "gacha_amount": gacha_amount
                                }
                                {#document.getElementById("gacha_result_img").src = "../static/video/gacha_normal.mp4"#}
                                $.ajax({
                                    url: {{ url_for("Simulator.Simulator_Main") }},
                                    type: 'POST',
                                    data: JSON.stringify(post_data),
                                    dataType: 'JSON',
                                    contentType: 'application/json',
                                    success: function (data) {

                                        document.getElementById("gacha_result_img").src = data.result_data["src"]
                                        var gachaResultData = data.result_data["result"]

                                        for (result_num in gachaResultData) {
                                            var doll_data_dict = gachaResultData[result_num]
                                            var result_elem = document.getElementById("gacha_result_table")
                                            var data_elem_container = document.createElement("tr")

                                            var gacha_count_elem = document.createElement("td")
                                            var gacha_count_node = document.createTextNode(data.result_data["current_gacha_amount"] - 10 + parseInt(result_num))
                                            gacha_count_elem.appendChild(gacha_count_node)
                                            data_elem_container.appendChild(gacha_count_elem)


                                            var doll_name_data_elem = document.createElement("td")
                                            var doll_name_data_node = document.createTextNode(doll_data_dict["NAME"])
                                            doll_name_data_elem.appendChild(doll_name_data_node)
                                            data_elem_container.appendChild(doll_name_data_elem)

                                            var doll_grade_data_elem = document.createElement("td")
                                            var doll_grade_data_node = document.createTextNode(doll_data_dict["GRADE"])
                                            doll_grade_data_elem.appendChild(doll_grade_data_node)
                                            data_elem_container.appendChild(doll_grade_data_elem)

                                            var doll_element_data_elem = document.createElement("td")
                                            var element_data = doll_data_dict["ELEMENT"]
                                            if (element_data === "Saltstone") {
                                                var element_data_kr = "염석"
                                            } else if (element_data === "Brimstone") {
                                                var element_data_kr = "유황"
                                            } else {
                                                var element_data_kr = "수은"
                                            }
                                            var doll_element_data_node = document.createTextNode(element_data_kr)
                                            doll_element_data_elem.appendChild(doll_element_data_node)
                                            data_elem_container.appendChild(doll_element_data_elem)

                                            var doll_class_data_elem = document.createElement("td")
                                            var class_data = doll_data_dict["DOLL_CLASS"]
                                            if (class_data === "Guardian") {
                                                var class_data_kr = "수호형"

                                            } else if (class_data === "Destroyer") {
                                                var class_data_kr = "파괴형"

                                            } else if (class_data === "Mage") {
                                                var class_data_kr = "마도형"

                                            } else if (class_data === "Assassin") {
                                                var class_data_kr = "암살형"

                                            } else if (class_data === "	Healer") {
                                                var class_data_kr = "회복형"

                                            } else {
                                                var class_data_kr = "방해형"
                                            }
                                            var doll_class_data_node = document.createTextNode(class_data_kr)
                                            doll_class_data_elem.appendChild(doll_class_data_node)
                                            data_elem_container.appendChild(doll_class_data_elem)


                                            result_elem.appendChild(data_elem_container)
                                        }

                                    },
                                    error: function (request, status, error) {
                                        alert("가챠 결과 이미지를 가져오는 도중에 ajax 통신에 실패하였습니다.")
                                    }
                                })
                            })
                        </script>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>
    <img alt=" " id="gacha_result_img" src="../static/img/gacha/background/gacha_background.png" style=" max-width:100%; height:auto;">
{#    {% if session.get("banner") == "꿈의 소환" %}#}
{#        <img alt=" " id="gacha_result_img" src="../static/img/gacha/background/dream_gacha_background.png" style=" max-width: 60%; height:auto;">#}
{#    {% else %}#}
{#        <img alt=" " id="gacha_result_img" src="../static/img/gacha/background/gacha_background.png" style=" max-width:100%; height:auto;">#}
{#    {% endif %}#}


    {# 위의 이미지 태그는 base64인코딩된 바이너리 파일로 지정 #}
    {# 이미지와 밑에 가챠 결과는 post로 ajax요청을 받아서 실시간 업데이트를 진행해야함 #}

    <h2 style="margin-top: 20px; font-family: 'Black Han Sans', sans-serif">가챠 결과</h2>
    <div class="table-responsive overflow-auto" style="max-width: 100%; height: 350px">
        <table class="table table-striped table-sm">

            <thead>
                <tr>
                    <th id="gachaCount" scope="col" style="font-size: x-large">횟수</th>
                    {% if session.get("banner") == "레전더리 장비 상자" %}
                        <th scope="col" style="font-size: x-large">장비 이름</th>
                        <th scope="col" style="font-size: x-large">등급</th>
                        <th scope="col" style="font-size: x-large">장비 점수</th>
                    {% else %}
                        <th scope="col" style="font-size: x-large">인형</th>
                        <th scope="col" style="font-size: x-large">등급</th>
                        <th scope="col" style="font-size: x-large">속성</th>
                        <th scope="col" style="font-size: x-large">타입</th>
                    {% endif %}
{#                    {% block gacha_result_table %}#}
{#                    {% endblock %}#}

                </tr>
            </thead>


            <tbody id = "gacha_result_table">
            </tbody>

        </table>
    </div>
{% endblock %}

templates/Simulator/simulator_ajax_chest_gacha.html
{% extends "Simulator/Simulator.html" %}
{% block ajax_button %}
    <input type="button" class="btn btn-sm btn-outline-secondary" id="gacha_1"
                           style="font-family: 'Jua', sans-serif; font-size: large; margin-left: 8px; margin-bottom: 5px"
                           value="1회" data-gacha-amount="1">

    <script>
        $('#gacha_10').click(function (){
            var gacha_amount = $('#gacha_1').val()
            var post_data = {
                "gacha_amount": gacha_amount
            }
            {#document.getElementById("gacha_result_img").src = "../static/video/gacha_normal.mp4"#}
            $.ajax({
                url: {{ url_for("Simulator.Simulator_Main") }},
                type: 'POST',
                data: JSON.stringify(post_data),
                dataType: 'JSON',
                contentType: 'application/json',
                success: function (data) {

                    document.getElementById("gacha_result_img").src = data.result_data["src"]
                    var gachaResultData = data.result_data["result"]

                    for (result_num in gachaResultData) {
                    }

                },
                error: function (request, status, error) {
                    alert("가챠 결과 이미지를 가져오는 도중에 ajax 통신에 실패하였습니다.")
                }
            })
        })
    </script>
{% endblock %}

templates/Simulator/simulator_ajax_doll_gacha.html
{% extends "Simulator/Simulator.html" %}
{% block ajax_button %}
    <input type="button" class="btn btn-sm btn-outline-secondary" id="gacha_10"
                           style="font-family: 'Jua', sans-serif; font-size: large; margin-left: 8px; margin-bottom: 5px"
                           value="10회" data-gacha-amount="10">

    <script>
        $('#gacha_10').click(function (){
            var gacha_amount = $('#gacha_10').val()
            var post_data = {
                "gacha_amount": gacha_amount
            }
            {#document.getElementById("gacha_result_img").src = "../static/video/gacha_normal.mp4"#}
            $.ajax({
                url: {{ url_for("Simulator.Simulator_Main") }},
                type: 'POST',
                data: JSON.stringify(post_data),
                dataType: 'JSON',
                contentType: 'application/json',
                success: function (data) {

                    document.getElementById("gacha_result_img").src = data.result_data["src"]
                    var gachaResultData = data.result_data["result"]

                    for (result_num in gachaResultData) {
                        var doll_data_dict = gachaResultData[result_num]
                        var result_elem = document.getElementById("gacha_result_table")
                        var data_elem_container = document.createElement("tr")

                        var gacha_count_elem = document.createElement("td")
                        var gacha_count_node = document.createTextNode(data.result_data["current_gacha_amount"] - 10 + parseInt(result_num))
                        gacha_count_elem.appendChild(gacha_count_node)
                        data_elem_container.appendChild(gacha_count_elem)


                        var doll_name_data_elem = document.createElement("td")
                        var doll_name_data_node = document.createTextNode(doll_data_dict["NAME"])
                        doll_name_data_elem.appendChild(doll_name_data_node)
                        data_elem_container.appendChild(doll_name_data_elem)

                        var doll_grade_data_elem = document.createElement("td")
                        var doll_grade_data_node = document.createTextNode(doll_data_dict["GRADE"])
                        doll_grade_data_elem.appendChild(doll_grade_data_node)
                        data_elem_container.appendChild(doll_grade_data_elem)

                        var doll_element_data_elem = document.createElement("td")
                        var element_data = doll_data_dict["ELEMENT"]
                        if (element_data === "Saltstone") {
                            var element_data_kr = "염석"
                        } else if (element_data === "Brimstone") {
                            var element_data_kr = "유황"
                        } else {
                            var element_data_kr = "수은"
                        }
                        var doll_element_data_node = document.createTextNode(element_data_kr)
                        doll_element_data_elem.appendChild(doll_element_data_node)
                        data_elem_container.appendChild(doll_element_data_elem)

                        var doll_class_data_elem = document.createElement("td")
                        var class_data = doll_data_dict["DOLL_CLASS"]
                        if (class_data === "Guardian") {
                            var class_data_kr = "수호형"

                        } else if (class_data === "Destroyer") {
                            var class_data_kr = "파괴형"

                        } else if (class_data === "Mage") {
                            var class_data_kr = "마도형"

                        } else if (class_data === "Assassin") {
                            var class_data_kr = "암살형"

                        } else if (class_data === "	Healer") {
                            var class_data_kr = "회복형"

                        } else {
                            var class_data_kr = "방해형"
                        }
                        var doll_class_data_node = document.createTextNode(class_data_kr)
                        doll_class_data_elem.appendChild(doll_class_data_node)
                        data_elem_container.appendChild(doll_class_data_elem)


                        result_elem.appendChild(data_elem_container)
                    }

                },
                error: function (request, status, error) {
                    alert("가챠 결과 이미지를 가져오는 도중에 ajax 통신에 실패하였습니다.")
                }
            })
        })
    </script>
{% endblock %}

{% block gacha_result_table %}
    <th scope="col" style="font-size: x-large">인형</th>
    <th scope="col" style="font-size: x-large">등급</th>
    <th scope="col" style="font-size: x-large">속성</th>
    <th scope="col" style="font-size: x-large">타입</th>
{% endblock %}